[gcp_service_account]
client_id = "584727346051-ciggpcgmjnvtoqr4dt8kc0pepgqt0g1s.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "https://nba-pra-app.streamlit.app/oauth2callback"

[google_sheets]
default_sheet_name = "NBA_Prop_Model_Log"
